quarkus:
  amqp:
    devservices:
      enabled: false
  datasource:
    devservices:
      enabled: false
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://localhost:3306/test
    username: root
    password: adminconsultant
  hibernate-orm:
    database:
      generation: update


# The AMQP broker location and credentials
amqp-host: localhost
amqp-port: 5672
amqp-username: guest
amqp-password: guest
amqp-virtual-host: /

## Configuring the incoming channel (reading from AMQP)
#mp.messaging.incoming.movies-in.connector: smallrye-amqp
#mp.messaging.incoming.movies-in.address: movies

# Configuring the outgoing channel (writing to AMQP)
mp:
  messaging:
    outgoing:
      fruits-out:
        connector: smallrye-amqp
        exchange:
          name: fruits-input
        queue:
          name: fruits-input
          durable: true